import React, { useEffect, useState } from "react";
import { Megaphone, Plus, Trash2 } from "lucide-react";
import api from "../../../shared/services/api";
import notify from "../../../shared/utils/toast";
import "../admin.css";

type Coupon = { id: string; code: string; discount_type: string; discount_value: number; min_order_amount: number };
export const Campaigns: React.FC = () => {
  const [coupons, setCoupons] = useState<Coupon[]>([]); const [code, setCode] = useState(""); const [type, setType] = useState("percentage"); const [value, setValue] = useState(""); const [minimum, setMinimum] = useState(""); const [loading, setLoading] = useState(false);
  const load = async () => { try { const { data } = await api.get("/admin/coupons"); setCoupons(data.data || []); } catch { notify.error("Couldn't load campaigns."); } };
  useEffect(() => { load(); }, []);
  const create = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); try { await api.post("/admin/coupons", { code, discount_type: type, discount_value: Number(value), min_order_amount: Number(minimum || 0), start_date: new Date().toISOString().slice(0, 10), end_date: new Date(Date.now() + 30 * 86400000).toISOString().slice(0, 10) }); notify.success("Campaign published."); setCode(""); setValue(""); setMinimum(""); load(); } catch (error: any) { notify.error(error.response?.data?.message || "Couldn't publish campaign."); } finally { setLoading(false); } };
  const remove = async (id: string) => { if (!window.confirm("Remove this campaign?")) return; try { await api.delete(`/admin/coupons/${id}`); setCoupons((items) => items.filter((item) => item.id !== id)); notify.info("Campaign removed."); } catch { notify.error("Couldn't remove campaign."); } };
  return <div className="campaigns-page"><div className="workspace-title"><div><p className="operations-kicker">Growth workspace</p><h1>Campaigns</h1><p>Design simple, controlled incentives for the Bites marketplace.</p></div><div className="workspace-title-icon"><Megaphone/></div></div><div className="campaigns-grid"><section className="workspace-panel"><div className="workspace-panel-header"><div><p className="panel-eyebrow">New campaign</p><h2>Create a promo code</h2></div></div><form className="campaign-form" onSubmit={create}><label>Code<input required value={code} onChange={(e) => setCode(e.target.value.toUpperCase())} placeholder="BITES50"/></label><label>Discount type<select value={type} onChange={(e) => setType(e.target.value)}><option value="percentage">Percentage</option><option value="fixed">Fixed amount</option></select></label><div className="campaign-form-row"><label>Value<input required type="number" min="1" value={value} onChange={(e) => setValue(e.target.value)} placeholder="50"/></label><label>Minimum order<input type="number" min="0" value={minimum} onChange={(e) => setMinimum(e.target.value)} placeholder="299"/></label></div><button className="campaign-submit" disabled={loading}><Plus size={17}/>{loading ? "Publishing…" : "Publish campaign"}</button></form></section><section className="workspace-panel"><div className="workspace-panel-header"><div><p className="panel-eyebrow">Live now</p><h2>{coupons.length} active campaigns</h2></div></div><div className="campaign-list">{coupons.length ? coupons.map((coupon) => <div className="campaign-row" key={coupon.id}><div><strong>{coupon.code}</strong><span>{coupon.discount_value}{coupon.discount_type === "percentage" ? "%" : "₹"} off · Min ₹{coupon.min_order_amount}</span></div><button onClick={() => remove(coupon.id)} aria-label={`Remove ${coupon.code}`}><Trash2 size={16}/></button></div>) : <div className="queue-empty">No active campaigns yet.</div>}</div></section></div></div>;
};
